aniketsinha2002/DataGeek

- Form/logsig.html
- Form/logsigh.css
- index.html
- created a login form through which users can login to the datascience website
- Fixed links redirection issue
> [New Feature]: Created Login form & [BUG FIXED]

- CONTRIBUTING.md
- README.md
Corresponds to the issue #9 to make streamlined and succinct files for `README.md` and `CONTRIBUTING.md`
> Improving on the README.md and CONTRIBUTING.MD file

- css/style.css
- index.html
CHANGES DONE✳
SOCIAL ICONS ARE NOW IN A STABLE POSITION🎨
Issue #11 solved
Kindly accept my PR.
> issue#11 Solved 🚀

- css/style.css
- index.html
closes #28
include font awesome icon cdn link and changed socials icon and size
and fixed the hover on the mail too.
and one typo.
> changes in footer section

- css/style.css
[fix] Add smooth scrolling for better UX 
- Added smooth scrolling to the website using CSS 3 scroll-behavior property.
- Added media query that effectively disables the scroll-behavior to auto on detection of 'reduced motion' preference from the user's browser.
> Solved #issue 18 - Added Smooth Scrolling behavior [GSSOC'23]

- css/style.css
closes #15 
https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/115306535/97d7184e-cb11-4182-8ff4-dfa693177646
> (#15) FAQ Section Animation added [GSSOC'23]

- css/style.css
Fixed basic CSS Validation Errors. Though logo class is not in use and border-image property is not necessary to use here.
> Fixed CSS Validation Errors

- index.html
- main.js
closes #48 
I have adjusted the scroll position of each section on the page.
> Adjust scroll height

- .vscode/settings.json
- css/style.css
closes #20 
image not coinciding with eath other
> Image problem solved

- index.html
- Replaced dummy text in the DataScience section of the footer
- Removed duplicated of the social media icons
> fixed: removed duplicated social media icons replace dummy footer text

- css/style.css
the achievement section was not responsive earlier . I did that
earlier : 
now:
> improved responsiveness

- index.html
Added some more questions to the FAQ section to make it more informative. Somebody had already changed the lorem ipsum texts. So I added 4 more questions and answers on Data Science.
> More informative FAQ issue #102

- css/style.css
- index.html
- main.js
**I have submitted another pull request. In the previous one, there was a conflict because you had already merged some pull requests. In this new pull request, I made some changes to the index.html file. Specifically, I moved the social media icons from the div with the class "footer_4" to the div with the class "footer_1." As you can see in the screenshot (ss), this could be the reason for the conflict.**
----------------- 
Okay, so you had assigned me issue #46, which I have resolved. The issue was to add an email sending feature with validation, which has been implemented. Now, you cannot leave the field empty, and you can't send more than 3 emails. If you exceed the limit, you'll have to wait for 5 minutes before the next email can be sent. Additionally, I have also improved and …
>  I want to add an email sending feature to the "Contact Us" .  Resolves #46

- Form/logsig.html
- Form/logsigh.css
I added a return to home button on the login page which would allow users to go back to the home page and also cleaned up the missing social media icons in the login section 
overall, I made changes in the login section of the website
> Added a return to home button and social media icons on login page 

- css/style.css
- index.html
Issue #96 
I have enhanced the alignment of components within card elements, ensuring a visually pleasing and organized layout. This improvement enhances user experience and ensures consistency across the interface.
Screenshot ( Phone ): 
Screenshot (Tablet ): 
Screenshot ( Laptop and PC ): 
Also please add the tag "GSSOC23" under the issue and "gssoc23-accepted" after PR gets merged.
> Improved Alignment of Components within Card Elements

- index.html
> Fixed : issue #80 and Removed Unusual things from Footer

- index.html
Reverts aniketsinha2002/DataScienceWebsite.github.io#160
> Revert "Fixed : issue #80 and Removed Unusual things from Footer"

- css/style.css
- main.js
Reverts aniketsinha2002/DataScienceWebsite.github.io#146
> Revert "Added styling to scrollbar with hover functionality"

- css/style.css
- index.html
Reverts aniketsinha2002/DataScienceWebsite.github.io#137
> Revert "Added scroll to top button"

- Form/logsig.html
The Back Button in Login page wasnt working, It was showing Error, Now it is working completely
> modified the back button in login

- index.html
issue :
#184 
this was small mistake created
which may cause a problem.
fixed it
> removed script tag #184

- css/style.css
> [refactor] achievement section responsive

- index.html
Updated the FAQ as it was full of Lorem Ipsum Texts. Made it informative. It consists of 10 questions with proper answers. I had done it once before. But the website is reverted back. Also the FAQ section was missing from navbar so I added it.
> Updated the FAQ

- css/style.css
- index.html
- main.js
Fixes #100 
I have added the back to top button with progress feature. 
Screenshot:
Please review and suggest the necessary changes @aniketsinha2002
> back to top button added

- index.html
Added definition for "What is Data Science?" instead of "lorem"
> Definition to What is Data science? added

- .vscode/settings.json
- css/style.css
Hello,
[Screencast from 24-05-23 12:22:36 AM IST.webm](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/121503426/88740943-94d1-4813-ba18-d6353d475ff5)
> Fixed the Width overflow issue

- course.html
- index.html
In Footer Section, Email and tel no. was not link.
So, I just Added mailto feature to email with anchor tag<a>.
And tel feature to Contact No. also with anchor tag<a>.
> Just added mailto and tel link to mail and mobileno

- css/style.css
There was a sudden appearance of a horizontal scroll bar momentarily.
> Fixed the unhandled overflow-x

- index.html
> Nav links updated mihir maurya #325

- index.html
- main.js
**Description**
ADDED PURE COUNTER 
It will reach to the number starting from 0 till it which enhances the interaction and experience of user 
Do acknowledge and merge it   
https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/119532943/dc3241d7-0caf-43fc-9ae9-0b47da175dc6
> Added pure counter to the achievement section 

- css/style.css
- index.html
- main.js
Reverts aniketsinha2002/DataScienceWebsite.github.io#79
> Revert "Fixed Issue #44 : adding light theme"

- contact/index.html
- contact/style.css
In contact page , your message section is going out of card and not looking good.
Please assign me to fix this issue.
> In Contact page , Your Message section is cross the card

- index.html
Hello @aniketsinha2002,
I'hv fixed the issue regarding the `footer` and the `contact form` unlinked.
So all things are fixed you can `merge` it -
[Screencast from 24-05-23 12:32:17 PM IST.webm](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/121503426/37678bc7-53ca-4e2e-ba95-273e9e6a40e0)
> Fixed footer issue | Contact form & Copyright |

- css/style.css
- index.html
Hello @aniketsinha2002 ,
Hero page is successfully fixed.
> `Hero page fixed`

- contact/style.css
> Correct the submit button in proper placed

- css/style.css
https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/106317680/1ca05cbd-0a4e-4ac0-96a8-a5900a3dca69
I have changed the layout of the questions to vertical, added a hover effect on each question, added animation to the icon on hover, and made the corners rounded for better visual appeal
issue #136
> made changes in appearance of the FAQ section

- .vscode/settings.json
- index.html
Hello @aniketsinha2002 ,
Here is the updated version of chatbot. 
[Screencast from 26-05-23 01:01:26 AM IST.webm](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/121503426/5721a378-ef99-456f-865e-c9e5ac5546cf)
> Added `Chat bot` {with optimized code}

- css/style.css
- index.html
- main.js
Hello @aniketsinha2002 ,
Added a type writer effect in the home page using **Advance JavaScript**
[Screencast from 26-05-23 05:35:46 PM IST.webm](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/121503426/5292a0f9-153f-4fa2-b56c-892c0f140081)
> Added `Type Writer` in the Home Page

- css/style.css
- index.html
- main.js
Hello @aniketsinha2002 ,
Added a cool feature again, now the copyright name is clickable.
[Screencast from 26-05-23 04:55:02 PM IST.webm](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/121503426/fecf7b86-64b1-4036-999c-17ed531b4fe8)
**When we hover it will bring a underline on the name and when we click it will open github profile of you**
- ### It is super ready to merge.
> Clickable `Copyright` added

- course.html
- courses.css
- css/style.css
In the main branch, as you can see spacing of navbar items are not proper. "Content" tab is out of the display, and padding between each tab is more than required.
So, I created a branch "space_nav_splusb", to deal with this problem. And in this case, I adjusted the spacing between contents by adding proper padding, changing width of the navbar. 
Also I fix the height of the navbar heading by adding margin top and bottom.
This is the result after inserting proper changes:
So, I hope this change is helpful to the website.
> Adjustment of proper alignment and spacing of navbar contents

- chatbot/script.js
- chatbot/style.css
- index.html
> [FIXED] ChatBot Design

- css/style.css
**Description**
In the home page get started and social media icons were randomly placed . I have done their alignment correct 
**Earlier**
**Now**
> Home Page alignment done correct(Screenshot attached)

- index.html
- smoothscroll.js
Hello, @aniketsinha2002. I have made some improvements to the code and added a smooth scroll feature that provides users with a seamless navigation experience when clicking on links in the navigation bar. I believe this enhancement would greatly benefit our project. Therefore, I kindly request you to consider merging this pull request. 
https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/78635373/5c021824-8cab-4007-8877-105f485ecef9
> Smooth Scroll feature

- css/style.css
- index.html
I changed the style of signup button and also when we hover it color changes and box shadow is also added  please consider this i am also a  contributor in GSSOC-23"
> We can view the signup button clearly 

- css/style.css
- index.html
like i changed the color of data science , primacy , contact us and ……when you mouseover on it it will change the color and its letter size also increases. and also same process for the links like home , about , courses , contact , and also links in primacy
> Added the hover effect in the footer section

- README.md
As I was assigned to enhance the README file #203, I have worked on it and would like you to view the file.
> Gummitha anushka patch 1

- course.html
- index.html
**BEFORE Modification:**
**Live Code:**
```
<body>
<nav></nav>
<section></section>
<section></section>
<section></section>
<section></section>
<section></section>
<footer></footer>
<div></div>
<div></div>
<script></script> ----> Multiple <script>Sections Here
</body>
```
**AFTER Modification:**
**Live Code:**
```
<body>
<header>
<nav></nav>
</header>
<main>
<section></section>
<section></section>
<section></section>
<section></section>
<section></section>
</main>
<footer></footer>
<div></div>
<div></div>
<script></script> ----> Multiple <script>Sections Here
</body>
```
**Explaination:** 
- Put Entire` <nav</nav> `section inside `<header></header>` section.
- Wrapping around Total 5 `<section></section>`elements  in` <main></main> `section.
- These above changes are better practice for …
> Semantic Errors-HTML5

- course.html
**BEFORE Modification:**
**Live Code:**
```
<body>
<nav></nav>
<div></div>
<section></section>
<section></section>
<section></section>
<section></section>
<div>
<section></section>
</div>
<footer></footer>
</body>
```
**AFTER Modification:**
**Live Code:**
```
<body>
<header>  
<nav></nav>
</header>
<main>
<section></section> ---> Replaced <div></div> with <section></section> Element
<section></section>
<section></section>
<section></section>
<section></section>
</main>
<div>
<section></section>
</div>
<footer></footer>
</body>
```
**Explaination:** 
1. Above order of the code, Modified Semantic Errors using Section like` <header></header>` and` <main></main>`.
2. Put `<nav></nav>` Tag in` <header></header>` section and Total 5 sections wrapping around by using `<main></main>`.
3. These …
> Modified Semantic Errors-HTML5

- courses.css
fixing nav bar at left side logo and the right side the navs
> navbar fix

- index.html
- main.js
https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/104729493/265ba382-762a-4e70-b61d-d1a39ac84c8e
kindly review @aniketsinha2002
> scroll_to_top_button problem solved  ..... issue #470

- courses.css
- css/style.css
> Changed the alignment of the navbar

- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/doc_issue.yaml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/pull_request_template.md
- Added 3 issue templates.
- Pull Request template (.github/pull_request_template.md)
> Issue and pull request template added (.github)

- css/style.css
- index.html
when you click on these icons you will be navigated to respected websites please consider this under GSSOC -23
> Adding Social media icons 

- css/style.css
- index.html
> Updated bootstrap class for css.
> Add Script for responsive behaviour of navbar
> Fixed: Issue#501 Improve Navbar and Space below Navbar

- css/style.css
- index.html
Reverts aniketsinha2002/DataScienceWebsite.github.io#525
> Revert "Fixed: Issue#501 Improve Navbar and Space below Navbar"

- sitemap.xml
This pull request adds a sitemap.xml file to the website, addressing the problem of the current lack of a sitemap. The sitemap.xml file is automatically generated and updated, following the XML sitemap protocol. This addition improves search engine optimization (SEO) and enhances user experience by enabling better navigation and content discovery.
In the attached screenshot, I have highlighted the website name with the expected presence of a sitemap.xml file. However, upon inspection, it is evident that the sitemap is not being displayed. This screenshot underscores the problem of the current website lacking a visible sitemap, further emphasizing the need for its implementation.
> Create sitemap.xml file for website

- css/style.css
- index.html
- main.js
This pull request addresses the flow-related issues in the website by implementing necessary fixes and improvements. The changes made significantly enhance the user experience and ensure smoother navigation throughout the site. Mainly worked on the landing page and fixed the flow of the website along with the "get started" button.
**Updated website**
> [553enhanced] Fixed Flow of Website

- contact/index.html
- index.html
- login/index.html
Completed SEO, no dependencies. 
As this is recurring process, I'll create an new issue after 10 days to update the SEO of new pages added.
NA
> Complete SEO of Website is Done

- css/style.css
- [yes ] Tests have been added or updated to cover the changes
- [ yes] Documentation has been updated to reflect the changes
- [yes ] Code follows the established coding style guidelines
- [ yes] All tests are passing
> bud is resolved now website is not broken 

- .github/workflow/issue-assign.yml
The Auto Issue Assignment feature is designed to automate the assignment of issues in a GitHub repository based on specific criteria. By leveraging GitHub Actions, this feature enables the automatic assignment of issues to users who meet predefined conditions, streamlining the issue management process and ensuring prompt attention to problems or tasks.
**Screen Shot -**
-  Tests have been added or updated to cover the changes
-  Documentation has been updated to reflect the changes
-  Code follows the established coding style guidelines
-  All tests are passing
> Auto assign feature added

- css/style.css
The nav items are brought into the viewport display.
> navbar update

- css/style.css
- main.js
When the page is loaded scrollBtn is hidden when move down it going to be visible solved #614
> scrollBtn back to top issue is fixed

- .github/workflow/auto-comment.yml
Currently, when someone opens a new issue or pull request in a GitHub repository, there is no automated way to provide an immediate response or acknowledgment. As a result, contributors might be left wondering if their contribution was noticed or if it's being addressed.
With the "Auto Comment" feature, the repository owners and maintainers can set up a predefined comment that will automatically be posted as a reply to the newly opened issues and pull requests. This automated response will serve as a quick thank-you message or setting the right expectations for further interactions.
> Auto comment on issue feature added

- contact/index.html
- index.html
- login/index.html
Added meta tags like language, author, revisit-after, open graph, twitter tags, etc
> Added meta tags

- css/style.css
Added a new hover effect animation with a transition and transformation.
To added a hover effect in footer socials
> added a hover effect in footer socials

- .github/workflow/pr-auto-comment.yml
The "Pull Request Auto-Comment" feature is an automated mechanism implemented using GitHub Actions to provide automatic comments on newly opened pull requests in a GitHub repository. When a user creates a new pull request, the system triggers a GitHub Actions workflow specifically designed to listen for "pull_request: opened" events. Upon detection of such an event, the workflow executes a predefined script, which adds a comment to the newly opened pull request.
The benefits of this feature are:
- Instant Feedback and Appreciation
- Automated Workflow
> Pull request Auto comment feature added

- css/style.css
- Fixed the broken header background
> fix: broken header background 🛠

- .github/workflow/codeql.yml
CodeQL is a powerful static analysis tool developed by GitHub that allows developers to analyze their codebases for potential bugs, security vulnerabilities, and other code quality issues. It uses a declarative query language called QL to define and execute queries on the codebase. While CodeQL is often associated with security analysis, it can also be used for general code quality improvements.
Here's a breakdown of how CodeQL features can be utilized in a This repository:
- Automated Code Scanning
- CodeQL Queries
- Security and Code Quality Rules
> Codeql Workflow Added

- index.html
I have added courses under the courses section. They open in a new tab which is user-friendly.
> #683 Courses added under courses section

- .github/workflows/Issue_Template/bug_report.md
- .github/workflows/Issue_Template/project_request.md
- .github/workflows/Issue_Template/pull_request_template.md
- .github/workflows/Issue_Template/update_request.md
I have added issue and pull request template in GitHub workflows,it will help in merging and keeping track of PR and issues .
Done under gssoc'23
Please review my pr and merge it . Thankyou!
1.
2.Update_Request_template.md
3. Project_Request_template
- [ Yes] Tests have been added or updated to cover the changes
- [ Yes] Documentation has been updated to reflect the changes
- [Yes] Code follows the established coding style guidelines
- [ Yes] All tests are passing
> [Gssoc'23] Added issue and pull request template in workflows 

- css/style.css
changes made in navbar [ fixed the navbar position and now signup button is visible to the navbar.] PR de58017b3c4dd92ef4c539e2c59fda0681565e13
Before:
After: 
- [Yes ] Tests have been added or updated to cover the changes
- [ YEs] Documentation has been updated to reflect the changes
- [ Yes] Code follows the established coding style guidelines
- [ Yes] All tests are passing
> [Gssoc'23] Fixed the navbar issue

- index.html
I changed the links in the footer section so that they get directed to the respective sections.
> #689 Footer update

- css/style.css
- index.html
Our popular courses section ui improved and added rate our courses section
https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/119532943/f708a04b-6d0f-419d-bc1d-5076e3075a5f
- [x ] Tests have been added or updated to cover the changes
- [ x] Documentation has been updated to reflect the changes
- [x ] Code follows the established coding style guidelines
- [x ] All tests are passing
> our courses improved & added animated rate our course (video attached)

- css/style.css
- index.html
Reverts aniketsinha2002/DataScienceWebsite.github.io#602
> Revert "our courses improved & added animated rate our course (video attached)"

- index.html
Made some minor changes in the footer section, Footer section was showing the CSS or something via github, I tried to fix that, was working for me.
> Minor Bugs and Fixes

- css/style.css
Corrected Padding of the footer
> Padding corrected

- contact/index.html
- contact/style.css
Added navbar in contact us page . Please review my PR 390e7fe9d71666ea2cf7528320e0a39915355533
before:-<img width="858" alt="image" src="https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/114860158/8a190d99-8b94-4913-8dbc-5f1c3b9f171d">
after:-
solution vedio:-
https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/114860158/098e2612-ac92-4437-acaf-e94e909ae0f4
- [ Yes] Tests have been added or updated to cover the changes
- [ Yes] Documentation has been updated to reflect the changes
- [ Yes] Code follows the established coding style guidelines
- [ Yes] All tests are passing
> [Gssoc'23]Added navbar in contact us page #693

- contact/index.html
https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/114687502/a0fa99d9-3e1f-4481-a81e-0aba6c370056
- [x ] Tests have been added or updated to cover the changes
- [ x] Documentation has been updated to reflect the changes
- [x ] Code follows the established coding style guidelines
- [x ] All tests are passing
> updated contact us now animation works properly.

- contact/index.html
the changes i did are 
added links in navbar in contact page
https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/96969496/3c7110c1-e8ba-44d2-bc6c-a737575f0831
> links updated

- .github/workflow/close_old_issues.yml
- .github/workflow/issues.yml
- .github/workflow/linting.yml
- .github/workflow/lock.yml
- .github/workflow/prevent_multiple_issues.yml
- **Added issues.yml, close_old_isuues.yml, prevent_old_issues.yml, lock.yml and linting.yml Files in workflows Sub-Folder existed in .github Parent Folder in Project Directory**
Replace ` #708 ` with the issue number which is fixed in this PR
> feat: Added Multiple workflows in GitHub Workflows Folder

- contact/index.html
> footer is added at contact section

- contact/index.html
- contact/style.css
https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/114860158/a87e71b5-85b1-413b-8349-8b9a24489971
- [ X] Tests have been added or updated to cover the changes
- [ X] Documentation has been updated to reflect the changes
- [ X] Code follows the established coding style guidelines
- [ X] All tests are passing
> update Contact page navbar buttons working #719

- css/style.css
Centered all the elements in the course containers
> Centered the elements on the course containers

- Team/team.css
- Team/team.html
- Team/team.js
- index.html
Added the Contributor List.
Fixed the issue #724 . 
Video : 
https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/127319225/154163a2-d5ff-4827-ab0a-8607c6c271a8
Just a small request, please consider this issue to be of level 3 . It will help me very much.
Thank You
- [ x] Tests have been added or updated to cover the changes
- [ x] Documentation has been updated to reflect the changes
- [ x] Code follows the established coding style guidelines
- [x ] All tests are passing
> Added Contributers List to the website

- index.html
> footer improved

- css/bot.css
- css/style.css
- index.html
I have implemented the chatbot successfully and it is looking appealing as a visitor.
I have implemented the chatbot in the website using HTML, CSS, and JavaScript.
> [FEATURE] <description> #741 Resolved

- contact/style.css
- css/style.css
Fixed faq section cards and text, also made it responsive
Now its not touching the edges
Before - 
After -
> Improved frequently asked section cards and made it responsive 

- contact/style.css
- css/style.css
I have contact us page look for mobile screen and remove that unnecessary space from the top
@aniketsinha2002 
Before
After
> fixed spacing issue in the contact us page

- contact/style.css
I changed the distance between Navbar & Contact Us.
Steps -
1. Go to Home-page.
2. then Go to Contact-page.
3. See Fixes.
Fixes #750
Replace #750 with the issue number which is fixed in this PR
> Fixes - Fixes the issue of touchiness between Navbar & Contact Us

- css/style.css
> Fix the card margin problem

- contact/index.html
- contact/style.css
> Issue is fixed in contact page

- css/style.css
I have fixed footer responsiveness @aniketsinha2002 
> Footer fixed

- Team/team.css
- Team/team.html
- Team/team.js
@aniketsinha2002  I have fixed contributors page and added github url of contributors
Kindly merge it :)
> contributors page improved and added github url

- login/index.html
- login/signup.js
- Info about the related issue
Closes: #232
There were no signUp functionalities on this website so i added one.
I have added it from firebase Authentication for web apps. I have only added signUp function and not login. In signUp also i haven't made it to redirect to home page as the home page still contains signUp button which should be changed to SignOut. I am a first time contributer so may be there could be some mistakes. But the SignUp thing is working fully that is for sure.
One more thing is that the appdetails list in signup.js are my own credentials so everytime a user Signs up it shows up in my firebase console the owner will have to replace it with there own credentials rest code can remain same.
For verification i have added alert('signup successful') to indicate if signup is …
> added sign up functionality

- css/style.css
- index.html
added underline button hover effect in Navbar 
<! -- Mark the completed tasks with [x] -->
> added feature underline button Hover Effects

- courses.css
- css/style.css
- index.html
> Revert "Animated Hover Button"

- css/style.css
Transition effect on card when hovering on it is added.
on hovering on this card it moves up
> Transition effect on card

- contact/index.html
- contact/style.css
- css/style.css
- index.html
Reverts aniketsinha2002/DataGeek#771
> Revert "Updated FAQs and contact section with redirect fixes on navbar"

- Team/team.css
- Team/team.html
- contact/index.html
- contact/style.css
- css/style.css
- index.html
Updated Navbar view on contact and team section. A common navbar is shown for navigation to all site pages with redirect fixes on navbar.
https://github.com/aniketsinha2002/DataGeek/assets/66515549/cfdead3c-1793-41d2-b6c3-6295784c2dc4
> Resolved Conflicts - Updated Navbar view on contact and team section with redirect fixes on navbar

- index.html
> updated h1 

- contact/index.html
- course.html
- index.html
updated the copyright year to current year 2024 which was earlier 2023
**before
**
**after
**
Fixes #781 
close #781 
- [x ] Tests have been added or updated to cover the changes
- [ x] Code follows the established coding style guidelines
please add all the labels
hacktoberfest 
ggsoc
level 2 or level 3
> update copyright year to 2024
